Title : Chapter 7 26-05-2025

In [2]:
import pandas as pd
import seaborn as sns

'''Ignore warnings'''
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [3]:
df = sns.load_dataset('tips');
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [ ]:
df['size'].unique()

array([2, 3, 4, 1, 6, 5])

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
df['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [ ]:
df['size'].value_counts(normalize=True)

size
2    0.639344
3    0.155738
4    0.151639
5    0.020492
1    0.016393
6    0.016393
Name: proportion, dtype: float64

In [ ]:
df['size'].value_counts(normalize=True)

size
2    0.639344
3    0.155738
4    0.151639
5    0.020492
1    0.016393
6    0.016393
Name: proportion, dtype: float64

In [ ]:
df['total_bill'].value_counts(bins=10,sort=False)

(3.021, 7.844]       7
(7.844, 12.618]     42
(12.618, 17.392]    68
(17.392, 22.166]    51
(22.166, 26.94]     31
(26.94, 31.714]     19
(31.714, 36.488]    12
(36.488, 41.262]     7
(41.262, 46.036]     3
(46.036, 50.81]      4
Name: count, dtype: int64

In [ ]:
df['sex'].replace('Male','M', inplace=True)
df['sex'].replace('Female','F',inplace=True)

In [ ]:
df

     total_bill   tip sex smoker   day    time  size
0         16.99  1.01   F     No   Sun  Dinner     2
1         10.34  1.66   M     No   Sun  Dinner     3
2         21.01  3.50   M     No   Sun  Dinner     3
3         23.68  3.31   M     No   Sun  Dinner     2
4         24.59  3.61   F     No   Sun  Dinner     4
..          ...   ...  ..    ...   ...     ...   ...
239       29.03  5.92   M     No   Sat  Dinner     3
240       27.18  2.00   F    Yes   Sat  Dinner     2
241       22.67  2.00   M    Yes   Sat  Dinner     2
242       17.82  1.75   M     No   Sat  Dinner     2
243       18.78  3.00   F     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
df.sort_values(by='total_bill',ascending=False,ignore_index=True)

     total_bill    tip     sex smoker   day    time  size
0         50.81  10.00    Male    Yes   Sat  Dinner     3
1         48.33   9.00    Male     No   Sat  Dinner     4
2         48.27   6.73    Male     No   Sat  Dinner     4
3         48.17   5.00    Male     No   Sun  Dinner     6
4         45.35   3.50    Male    Yes   Sun  Dinner     3
..          ...    ...     ...    ...   ...     ...   ...
239        7.51   2.00    Male     No  Thur   Lunch     2
240        7.25   1.00  Female     No   Sat  Dinner     1
241        7.25   5.15    Male    Yes   Sun  Dinner     2
242        5.75   1.00  Female    Yes   Fri  Dinner     2
243        3.07   1.00  Female    Yes   Sat  Dinner     1

[244 rows x 7 columns]

In [9]:
df.sort_values(['size','total_bill'])

     total_bill   tip     sex smoker   day    time  size
67         3.07  1.00  Female    Yes   Sat  Dinner     1
111        7.25  1.00  Female     No   Sat  Dinner     1
222        8.58  1.92    Male    Yes   Fri   Lunch     1
82        10.07  1.83  Female     No  Thur   Lunch     1
92         5.75  1.00  Female    Yes   Fri  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
156       48.17  5.00    Male     No   Sun  Dinner     6

[244 rows x 7 columns]